services:
  demoapp:
    container_name: 'demoapp'
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8000:8000
    expose:
      - 8000
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3